---
- name: fetch latest git version
  git:
    repo: "https://github.com/j-chimienti/pollofeed.git"
    update: yes
    dest: "./{{APP_DIR}}"


- name: cron
  include: cron.yml
  when: false


- name: env files
  when: true
  include: copyEnv.yml


- name: reboot
  when: true
  include: reboot.yml
