version: '3.4'
services:
    db:
      container_name: db
      image: mongo
      volumes:
        - /mongo/data/pollofeed:/data/db
      env_file:
      - .env.mongo
      ports:
      - 27017:27017
      restart: always
      networks:
      - pollofeed
    pollofeed_app:
      healthcheck:
        test: "CMD curl -f http://localhost:${APP_PORT} || exit 1"
        interval: 30s
        timeout: 2s
        retries: 3
        start_period: 60s
      container_name: pollofeed
      build: .
      restart: unless-stopped
#      deploy:
#        replicas: 5
#        resources:
#          limit:
#            cpu: 0.1
#            memory: 100M
      depends_on:
      - db
      networks:
      - pollofeed
      - generated_default
      env_file:
      - .env.mongo
      - .env
      environment:
        MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/admin"
      ports:
      - "${APP_PORT}:${APP_PORT}"
networks:
  pollofeed:
  generated_default:
    external:
      name: generated_default


