version: '3.4'
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - /mongo/data/pollofeed:/data/db
    env_file:
      - .env.mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - nginxproxy
  pollofeed:
    container_name: pollofeed
    build: .
    restart: unless-stopped
    networks:
    - nginxproxy
    env_file:
    - .env
    - .env.mongo
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/admin"
    ports:
    - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"

networks:
  nginxproxy:
    external:
      name: nginxproxy


