version: '3.1'
services:
    db:
      container_name: db
      image: mongo
      volumes:
        - /mongo/data/pollofeed:/data/db
      env_file:
      - .env.mongo
      ports:
      - 27017:27017
      restart: always
      networks:
      - pollofeed
    pollofeed_app:
      container_name: pollofeed
      build: .
      restart: unless-stopped
      networks:
      - pollofeed
      - generated_default
      env_file:
      - .env.mongo
      - .env
      environment:
        MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/admin"
      ports:
      - "${APP_PORT}:${APP_PORT}"
networks:
  pollofeed:
  generated_default:
    external:
      name: generated_default


