---

- name: copy file
  copy:
    src: ngrok.service
    dest: /etc/systemd/system/ngrok.service

- name: create service
  command: systemctrl start ngrok

- name: enable on boot
  command: systemctrl enable ngrok

