  version: '3.4'
  services:
    metabase:
      external_links:
        - db
      volumes:
        - /metabase-data:/metabase-data
      container_name: metabase_pollofeed
      networks:
        - pollofeed
        - generated_default
      image: metabase/metabase
      ports:
        - "8788:3000"
      environment:
        JAVA_TIMEZONE: US/Eastern
        VIRTUAL_HOST: metabase.btcpal.online
        LETSENCRYPT_HOST: metabase.btcpal.online
        LETSENCRYPT_EMAIL: jchimien@gmail.com
        VIRTUAL_PORT: 8788
      restart: always
  networks:
    pollofeed:
      external:
        name: pollofeed_pollofeed
    generated_default:
      external:
        name: generated_default
